### ISSUE TITLE
Support specialization restriction

### ISSUE THREAD

**Issue by haste** [oUF-wow/oUF#123]
The first, 5.0.1.15464, MoP beta patch introduced a new event PLAYER_SPECIALIZATION_CHANGED and a new function GetSpecialization().

**Comment by Rainrider** [comment]
Anything more specific on this one?

**Comment by p3lim** [comment]
Both the function and the event are used in multiple elements, and there is no relevancy to the core.
Pretty much an ancient note that was left alone.

Closing this.
