### ISSUE TITLE
Power Color tag for Fontstrings

### ISSUE THREAD

**Issue by Kygos** [oUF-wow/oUF#247]
A tag similar to [raidcolor] but for power color (eg if Warrior then set FontColor to RGB 255, 0, 0)

Will help out rookies such as myself that can't grasp the PostUpdate Function quite yet.

**Comment by p3lim** [comment]
You can easily add this tag yourself:

```Lua
oUF.Tags.Events['powercolor'] = 'UNIT_DISPLAYPOWER'
oUF.Tags.Methods['powercolor'] = function(unit)
	local _, powerType = UnitPowerType(unit)
	return Hex(_COLORS.power[powerType] or _COLORS.power.MANA)
end
```
