### ISSUE TITLE
Possible bug in oUF\elements\threat.lua:43 with UnitThreatSituation()

### ISSUE THREAD

**Issue by goldpaw** [oUF-wow/oUF#249]
A user of my UI experienced a bug while walking from his shipyard to his garrison. The bug report seems to be in the elements/threat.lua file of oUF and related to the target of target frame. I am unable to reproduce the bug myself currently, but it looks like somehow the frame's unit is wrong or doesn't exist. 

Anyhow, here is the report he posted and the link to it:

http://wow.curseforge.com/addons/gui4/tickets/5-error-walking-from-shipyard-to-garrison/

1x gUI4_UnitFrames\libs\oUF\elements\threat.lua:43 Usage: UnitThreatSituation("unit" [, "mob"])
[C]: in function `UnitThreatSituation'
gUI4_UnitFrames\libs\oUF\elements\threat.lua:43 in function <gUI4_UnitFrames\libs\oUF\elements\threat.lua:36
(tail call): ?
gUI4_UnitFrames\libs\oUF\ouf.lua:158 in function <gUI4_UnitFrames\libs\oUF\ouf.lua:149
(tail call): ?
[C]: in function`Show'
FrameXML\SecureStateDriver.lua:83 in function <FrameXML\SecureStateDriver.lua:73
FrameXML\SecureStateDriver.lua:137 in function <FrameXML\SecureStateDriver.lua:119

**Comment by haste** [comment]
I can't see anything obvious based on the full error dump on curseforge.
There the value it complains is missing, is defined.

This also happens during the OnShow call, which checks if the unit exists,
so it shouldn't have been able to continue if the unit was nil.

I'll see if I can take a deeper look later today.

A user of my UI experienced a bug while walking from his shipyard to his
garrison. The bug report seems to be in the elements/threat.lua file of oUF
and related to the target of target frame. I am unable to reproduce the bug
myself currently, but it looks like somehow the frame's unit is wrong or
doesn't exist.

Anyhow, here is the report he posted and the link to it:

http://wow.curseforge.com/addons/gui4/tickets/5-error-walking-from-shipyard-to-garrison/

1x gUI4_UnitFrames\libs\oUF\elements\threat.lua:43 Usage:
UnitThreatSituation("unit" [, "mob"])
[C]: in function UnitThreatSituation'
gUI4_UnitFrames\libs\oUF\elements\threat.lua:43 in function
<gUI4_UnitFrames\libs\oUF\elements\threat.lua:36
(tail call): ?
gUI4_UnitFrames\libs\oUF\ouf.lua:158 in function
<gUI4_UnitFrames\libs\oUF\ouf.lua:149
(tail call): ?
[C]: in functionShow'
FrameXML\SecureStateDriver.lua:83 in function
<FrameXML\SecureStateDriver.lua:73
FrameXML\SecureStateDriver.lua:137 in function
<FrameXML\SecureStateDriver.lua:119

—
Reply to this email directly or view it on GitHub
<https://github.com/haste/oUF/issues/249>.

**Comment by Rainrider** [comment]
Please re-open if this occurs again.
