### ISSUE TITLE
Power/resource changes in Legion

### ISSUE THREAD

**Issue by p3lim** [oUF-wow/oUF#260]
This is just a compilation of all the information regarding power/resources for classes from the [Legion class previews](http://eu.battle.net/wow/en/blog/19941175), listing new/changed/removed powers/resources relevant to oUF.

## Additions

- Insanity
 - Shadow priests' new resource (replaces mana as primary resource)
 - Works like rage
 - Bar type element
- Lunar Power
 - Balance druids' new resource (replaces mana as primary resource)
 - Works like rage
 - Replaces Eclipse
 - Bar type element
- Arcane Charges
 - Arcane mages' "new" resource (class power)
 - It's basically the debuff turned into a proper class power
 - Pill type element
- Maelstrom
 - Elemental & enhancement shamans' new resource (replaces mana as primary resource)
 - Works like rage
 - Bar type element

## Changes

- Runes
 - Only one type now for all death knight specializations
 - Pill + bar type element (same as before)
- Chi
 - Only for windwalker monks
 - Pill type element
- Holy Power
 - Only for retribution paladins
 - Pill type element
- Soul Shards
 - Shared resource for all warlock specializations
 - Pill type element

## Removals

- Shadow Orbs
- Eclipse
- Holy Power (for protection and holy paladins)
- Chi (for brewmaster and mistweaver monks)
- Demonic Fury (although never implemented in oUF)
- Burning Embers (although never implemented in oUF)

## Notes

The following classes/specializations does not use mana as their primary resource any more.

- Shadow priests
- Balance druids
- Elemental & enhancement shamans
- Protection & retribution paladins

**Comment by p3lim** [comment]
With these changes, some resources can finally be merged into single elements (pill and bar).

- Pill (classicons element)
 - Combo Points (should have been merged into this element already, since it's not per-target any more)
 - Chi (already implemented, but will need specialization checks)
 - Soul Shards (already implemented, but will need to remove specialization checks)
 - Shadow Orbs (needs to be removed)
 - Arcane Charges
- Bar (classpowers (?) element)
 - Insanity
 - Astral Power
 - Maelstrom
 - Druid Mana (should be merged into this element)

The eclipsebar element needs to be removed.  
The runebar element needs to be changed, and depending on what changes has been made to them, could potentially be merged into the pills (classicons) element.  
The totems element might need some changes, won't know until beta.

Not considered is the Demon Hunter, as I have no idea what resources they are using.

**Comment by p3lim** [comment]
As for demon hunters, they will be using Fury (basically rage) as their primary resource, they don't seem to have any secondary resource.

**Comment by Rainrider** [comment]
This is a nice summary @p3lim, thank you!
Combo points were originally part of the classicons element but were removed. See @zorker's comment on https://github.com/haste/oUF/commit/a1f98d20d510ccd46d800a007827e02a1ad6180a

**Comment by p3lim** [comment]
@Rainrider Since @zorker made that comment CP has [been moved away from the target](http://wow.gamepedia.com/Combo_point#Patch_changes), atleast mechanically. In the default UI the CP are still shown on the target however, and the layout would still be free to do so post-merge.

**Comment by zorker** [comment]
Thanks p3lim. Not sure when the console/addons will be enabled in the beta. Could take some time. Extracting the FrameXML will probably a good source of information early on.

**Comment by p3lim** [comment]
> Extracting the FrameXML will probably a good source of information early on.

It's usually the only source of information, and I expect that we'd have to extract it with LuaCASC like last time because the console will probably be disabled for a while.

**Comment by p3lim** [comment]
"Astral Power" was renamed to "Lunar Power".

**Comment by p3lim** [comment]
Found a few more issues; tapping is deprecated (in the sense of how it used to work), and there seems to be an issue with portrait updates. Will test more when I get back home next week.
