### ISSUE TITLE
altpowerbar issue with tonk commander game in darkmoon faire

### ISSUE THREAD

**Issue by gagou** [oUF-wow/oUF#293]
When  playing the darkmoon faire game in DMF the altpower bar show then hide very quickly.

Looking at the calls to the Toggler function, it's called two times:
- first time by the UNIT_POWER_BAR_SHOW event and player unit, this result => alt power bar frame is shown.
- second time a few ms later by RefreshUnit with vehicle unit (so triggered by PLAYER_ENTER_VEHICLE), UnitAlternatePowerInfo return nil for vehicle in this case => alt power bar frame is hidden.

**Comment by zorker** [comment]
I checked alt power bars over the weekend and all I can say is fuck that. When the bar is player only no problems occur.

But oh boy...better let not vehicle interfere. You get all kinds of results. Depending on how fast you click on the vehicle exit (or whatever).

The culprit is 

    if unit ~= self.unit then return end

It cancels out the toggle or the bar update since it is either true for player or vehicle.

I set up my own module and played around with it a bit.
https://github.com/zorker/rothui/blob/master/wow7.0/oUF_Simple/modules/rAltPowerBar.lua

Added a bad unit function.

**Comment by ls-** [comment]
Nah, everything is a bit more complicated or simpler...

There's an issue w/ how oUF handles events/units, it always assumes that all elements use the same unit as their owner (unit frame), hence we have [UpdateUnits](https://github.com/oUF-wow/oUF/blob/master/events.lua#L17-L37) thingy.

But as we all can see now, that's not always the case. Although player frame's unit is replaced w/ `vehicle`, AltPowerBar elements needs `player` to work properly.

**Comment by ls-** [comment]
K, my current workaround is this:
```Diff
diff --git a/elements/altpowerbar.lua b/elements/altpowerbar.lua
index e95e93b..4bd5a35 100644
--- a/elements/altpowerbar.lua
+++ b/elements/altpowerbar.lua
@@ -65,7 +65,7 @@ local OnLeave = function()
 end
 
 local UpdatePower = function(self, event, unit, powerType)
-	if(self.unit ~= unit or powerType ~= 'ALTERNATE') then return end
+	if(not (self.realUnit and unit == self.realUnit or unit == self.unit) or powerType ~= 'ALTERNATE') then return end
 
 	local altpowerbar = self.AltPowerBar
 
@@ -132,7 +132,8 @@ local ForceUpdate = function(element)
 end
 
 local Toggler = function(self, event, unit)
-	if(unit ~= self.unit) then return end
+	if(self.realUnit and unit ~= self.realUnit or unit ~= self.unit) then return end
+
 	local altpowerbar = self.AltPowerBar
 
 	local barType, _, _, _, _, hideFromOthers, showOnRaid = UnitAlternatePowerInfo(unit)
```

But using `realUnit`s is ghetto...

**Comment by p3lim** [comment]
> But using `realUnit` is ghetto...

I second that.

**Comment by ls-** [comment]
Any suggestions? o_O

**Comment by Rainrider** [comment]
Register AltPower on the pet button in the layout. Sorry if this message
comes through multiple times

**Comment by zorker** [comment]
@Rainrider 
Imo that won't help. The toggle event starts with unit player but some time later the unit_power event will tell you about vehicle. Will experiment with it in the next days. A really good quest do test it is the flower zombie game quest in Hillsbrad (south of old Dalaran).

**Comment by ls-** [comment]
@zorker, it actually works, however, I have  a feeling that in some cases it may cause alt power bar duplicates, cuz same thingy often happens to player and pet castbars, when player is in some sort of vehicle.

**Comment by zorker** [comment]
Hmmm. Will try. Sounds wierd though and currently I do not have room for that bar in my layout.

**Comment by ls-** [comment]
You can try placing them on top of each other, cuz they're supposed to do same thing...

**Comment by Rainrider** [comment]
Both bars are different stuff. Those are the counter and the timer.

**Comment by zorker** [comment]
Tested it. Rainrider is totally correct. Adding the altpower bar to the pet aswell fixed all issues. Now I need to adjust my layout a tad bid. Overlaying is no option.

**Comment by Rainrider** [comment]
@zorker They can share the same position. When you are in a vehicle only the one for the pet frame is shown.

**Comment by zorker** [comment]
Ok will do.

**Comment by gagou** [comment]
I added AltPowerBar to the pet and it's now working perfectly.
My issue is solved.
