### ISSUE TITLE
Suggestion, new element: BuilderSpender

### ISSUE THREAD

**Issue by Sticklord** [oUF-wow/oUF#308]
This is the element that displays an overlay on the power bar when you gain/lose large portions (more than 10%) of your power, and also flashes when you're at maximum power, for rogues and demon hunters for example. Is this something that could be added?

This is my take on it, but I'm using most of blizzards methods and template because my frames look alot like the default ones. 

https://github.com/Sticklord/oUF_Abu/blob/master/Modules/oUF_BuilderSpender.lua

**Comment by Sticklord** [comment]
Yeah the blizzard implementation was kind of wierd with the onupdate of detecting if it should show etc. But it doesn't have much in common with the power prediction. The builderspender animates the gains/losses that has already happened, while the prediction, well, predicts the gain?/loss if the spell goes  trough. 

Maybe I'll draw up some sketch of it aswell.

**Comment by ls-** [comment]
@Sticklord, nah, that's fine. They tried to implement it as power prediction first, but sorta failed.

Main difference is abilities are instant casts, so you can't "predict", but fundamentally they're same thing.

**Comment by Sticklord** [comment]
Yeah when you put it like that i guess it makes sense :smile:

**Comment by ls-** [comment]
Hi!

So, after thinking about it for a while, I now think that it shouldn't be a part `PowerPrediction` element, cuz it'd be quite misleading, name like `PowerUsage` would be more befitting for it.

However, I'm not sure that  it should be a part of oUF either. Problem is that this thing relies on status bar "smoothing" to display info on power gain/loss, and bar animation IS NOT a part of oUF.

But we could implement a data provider type of element, if enabled it'd provide info on power gain/loss by measuring difference of power levels between `UNIT_SPELLCAST_SENT` and `UNIT_SPELLCAST_SUCCEEDED` events. And then layout could use provided data to do something fancy.

TBH, atm oUF has NO "data provider" elements, hence I'm not sure about adding one.

**Comment by p3lim** [comment]
No to the data provider element, that's middleware that is completely unnecessary.

The element however has a place in oUF, as oUF's mission was and still is to replicate all the default functionality of the standard unitframes.

**Comment by ls-** [comment]
@p3lim, yeah, I might be over-complicating things rn, hehe, and we all know the reason why...

It could be a widget similar to `PowerPrediction`, oUF would calculate and set all values, but layout would have to handle re-anchoring and animation via `PostUpdate`.

**Comment by ls-** [comment]
![](http://i.imgur.com/uYsO9hA.gif)

My progress so far... IT IS NOT power prediction. prediction shows power cost, before any change occurs. This thingy shows actual power gain and loss.

**Comment by ls-** [comment]
Closing this one too.

Please see first comment of #316 for more info on how to implement it in your layout.
