### ISSUE TITLE
Markdown documentation

### ISSUE THREAD

**Issue by Rainrider** [oUF-wow/oUF#320]
Review and convert documentation to markdown.

**Comment by p3lim** [comment]
Missing documentation in core:


#### ouf.lua

- [ ] oUF:RegisterInitCallback
- [ ] oUF:RegisterMetaFunction
- [ ] oUF:RegisterStyle
- [ ] oUF:SetActiveStyle
- [ ] oUF.IterateStyles
- [ ] oUF:SpawnHeader
- [ ] oUF:Spawn
- [ ] oUF:SpawnNamePlates
- [ ] oUF:AddElement
- [ ] oUF.version
- [ ] oUF.objects
- [ ] oUF.headers

- [ ] object:EnableElement
- [ ] object:DisableElement
- [ ] object:IsElementEnabled
- [ ] object:Enable
- [ ] object:Disable
- [ ] object:UpdateAllElements

#### units.lua

- [ ] oUF:HandleUnit

#### factory.lua

- [ ] oUF:Factory
- [ ] oUF:EnableFactory
- [ ] oUF:DisableFactory
- [ ] oUF:RunFactoryQueue

#### events.lua

- [ ] object:RegisterEvent
- [ ] object:UnregisterEvent

#### colors.lua

- [ ] oUF:RGBToHCY
- [ ] oUF:HCYtoRGB
- [ ] oUF.colors
- [ ] oUF.ColorGradient
- [ ] oUF.RGBColorGradient
- [ ] oUF.HCYColorGradient
- [ ] oUF.useHCYColorGradient

#### blizzard.lua

- [ ] oUF:DisableBlizzard

**Comment by p3lim** [comment]
Missing documentation in elements:

#### tags.lua

- Methods
- Callbacks
- Attributes
- Maybe look into documenting the available tags and their function (for wiki purposes).

**Comment by p3lim** [comment]
None of the elements has documentation for ForceUpdate.

**Comment by Rainrider** [comment]
`oUF:DisableBlizzard` and `oUF:HandleUnit` should probably not be exposed.
I have no idea how to document `oUF.colors` properly, because we'd have to describe the table keys too and the power element adds to this table too.
