### ISSUE TITLE
nameplates no more clickable after a while

### ISSUE THREAD

**Issue by gagou** [oUF-wow/oUF#328]
There was a bug with the standard wow nameplates and clique addon, after a while they were no more clickable, to fix this problem clique is no more registering nameplates.

Here is what is done in clique BlizzardFrames.lua :

>  -- skip the nameplates, they're TEHBROKEN
    if frame and frame.GetName and frame:GetName():match("^NamePlate") then
        return
    end

I think that we have the same problem with #312 when using clique, to fix this we need to avoid registering oUF nameplates frames with clique in initObject function.

**Comment by ls-** [comment]
I addressed this concern in #335.
