### ISSUE TITLE
[7.2.5] Destruction Soul Shards

### ISSUE THREAD

**Issue by Gethe** [oUF-wow/oUF#346]
Per the patch notes:
> Soul Shards are now divided into 10 Soul Shard Fragments for Destruction Warlocks ...

So Soul Shards for Destro Warlocks will be back to what they had in WoD, and would obviously have implications for the class icons element.

Now, while I would be willing to test this, I do not have a leveled Warlock and the PTR doesn't do premades anymore. That said, I'll try to level up a lock on the PTR as I have time.

**Comment by p3lim** [comment]
Should not need any modifications to the element, it works dynamically based on UnitPowerMax.

**Comment by Gethe** [comment]
Ah ok, thanks. Still though, I'd like to be sure.

**Comment by p3lim** [comment]
https://github.com/oUF-wow/oUF/blob/development/elements/classpower.lua#L83

**Comment by ls-** [comment]
I'm just passing by. Code wise nothing changed on PTR, however, there's only one issue, which is quite significant, default shard bars are `StatusBar`s, whereas ours are `Texture`s.

**Comment by Gethe** [comment]
Yes, but you are not using the third argument for that function. Without that, UnitPower[Max] will only return **full** soul shards, in order to get **partial** soul shards you have to pass in true as the third arg.

**Comment by ls-** [comment]
JIC, @Gethe  is talking about [this](https://github.com/Gethe/wow-ui-source/blob/ptr/FrameXML/ShardBar.lua#L103-L107)

```Lua
function WarlockPowerBar_UnitPower(unit)
	local shardPower = UnitPower(unit, Enum.PowerType.SoulShards, true);
	local shardModifier = UnitPowerDisplayMod(Enum.PowerType.SoulShards);
	return (shardModifier ~= 0) and (shardPower / shardModifier) or 0;
end
```

I explained entire situation in our gitter :p

**Comment by ls-** [comment]
@Gethe, yeah, I tested it too... I'd say there's no need to call `UnitPowerMax` w/ 3rd arg, it's easier to do something like this:
```Lua
local full, partial = math.modf(UnitPower("player", powerType, true) / UnitPowerDisplayMod(powerType))
```
ATM we're discussing if we want to convert all our classpowers to `StatusBar`s, jic, Blizz make more class power work this way in the future, or create a separate soulshards/shards/sharbar element.

**Comment by p3lim** [comment]
We'd support both of course, checking the type of the frame/object.

**Comment by p3lim** [comment]
Considering layouts need to support all classes and specs, textures are no longer viable for the classpower element.

**Comment by ls-** [comment]
RIP textures. 2006 - 2017. Never forget.

**Comment by ls-** [comment]
Done.

Closing this one.
