### ISSUE TITLE
Portraits Issue?

### ISSUE THREAD

**Issue by Aftermathhqt** [oUF-wow/oUF#389]
This error always happens to me either in Arena or Raids sometimes.

Message: ...e\AddOns\AftermathhUI\Libs\oUF\elements\portrait.lua:65: script ran too long
Time: 06/03/17 04:32:58
Count: 3
Stack: ...e\AddOns\AftermathhUI\Libs\oUF\elements\portrait.lua:65: in function <...e\AddOns\AftermathhUI\Libs\oUF\elements\portrait.lua:38>
(tail call): ?
Interface\AddOns\AftermathhUI\Libs\oUF\ouf.lua:200: in function `func'
Interface\AddOns\AftermathhUI\Libs\oUF\events.lua:50: in function <Interface\AddOns\AftermathhUI\Libs\oUF\events.lua:48>
(tail call): ?
[C]: in function `TargetUnit'
Interface\FrameXML\SecureTemplates.lua:483: in function `handler'
Interface\FrameXML\SecureTemplates.lua:619: in function `SecureActionButton_OnClick'
Interface\FrameXML\SecureTemplates.lua:659: in function <Interface\FrameXML\SecureTemplates.lua:651>

Locals: self = oUF_AftermathhTarget {
 0 = <userdata>
 UNIT_PORTRAIT_UPDATE = <function> defined @Interface\AddOns\AftermathhUI\Libs\oUF\elements\portrait.lua:83

**Comment by ls-** [comment]
IIRC, that's Blizzard bug and they aren't really sure what's causing it.

P.S. Cleaned up error log.

**Comment by p3lim** [comment]
You already posted this error and we explained to you why we cant fix it in #330.
