### ISSUE TITLE
One bug in the threatIndicator

### ISSUE THREAD

**Issue by siweia** [oUF-wow/oUF#390]
At the line 55:
status = UnitThreatSituation(unit)

Was it supposed to be "status = UnitThreatSituation('player', unit)" ?

**Comment by p3lim** [comment]
Without specifying the 2nd unit to compare against the function returns whichever mob the 1st unit has the highest threat against, and I believe that is the intended behavior we want with it.

**Comment by ls-** [comment]
It's not a bug, it's an intended change.

W/ 7.0.0 I added `.feedbackUnit` option for this particular reason. I recommend to use `element.feedbackUnit = "player"` for `"target"`, `"focus"` and `"boss*"` units in your layout code.

**Comment by siweia** [comment]
Thank you guys.
