### ISSUE TITLE
Class Power for Druid need not be complicated

### ISSUE THREAD

**Issue by selfaddicted** [oUF-wow/oUF#412]
https://github.com/oUF-wow/oUF/blob/56664f58b25464bf504039a370fb3e2e47165e75/elements/classpower.lua#L277

according to my own research, this spell is only available for feral druid which can get combo points. so checking spec and power(energy) should be enough

**Comment by Rainrider** [comment]
> Dump: value=GetSpellLevelLearned(5221)
[1]=10

It's there for a reason :)

**Comment by selfaddicted** [comment]
That spell is a default skill for feral druid and before level 10 a Druid can’t change his/her spec to feral; balance is default(?) spec. So if the conditions are met (feral spec and energy as power), we don’t need to register event to trace `SPELL_CHANGED` event

**Comment by p3lim** [comment]
The reason we're checking for the spell instead of the spec is because of the affinity talent.

**Comment by selfaddicted** [comment]
Ah.... my research wasn’t enough. Sorry to bother you guys. :)
