### ISSUE TITLE
inconsistent Castbar.casting value on nameplate units

### ISSUE THREAD

**Issue by decod3d** [oUF-wow/oUF#413]
I've noticed that _'frame.Castbar.casting'_ is set to true on some nameplates that are not casting (happens when you switch to a different target that is using the same nameplate unit - I think). 

It seems harmless at first sight (casting seems to do its work), but can result in bugs if you start relying on this variable in your own custom code.

**Comment by ls-** [comment]
The element was rewritten in #480 which indirectly addresses this issues.

Closing.
