### ISSUE TITLE
Auras count hidden when cooldown enabled

### ISSUE THREAD

**Issue by gempir** [oUF-wow/oUF#417]
When cooldown enabled on auras the count on the buff is hidden behind the cooldown.
https://i.imgur.com/ikF4VAj.png

If you look at the last buff (Bone Shield) you can see the count a tiny bit behind the 25.

**Comment by p3lim** [comment]
That would be the default cooldown text shown on every cooldown frame, by default.
oUF doesn't handle this at all, and it's up to the layout.

If you want to disable this, add the following to your aura frame's PostCreate callback:
```Lua
button.cd:SetHideCountdownNumbers(true)
```

**Comment by ls-** [comment]
Well, that's not oUF issue. 

It's up to you how to organise your frames. If you want to show stacks in front of CD timer, you'll need to create an overlay frame and use it as your count font string's parent.
