### ISSUE TITLE
Gray bar on Player & Target

### ISSUE THREAD

**Issue by joshckiley** [oUF-wow/oUF#425]
I do not know how to identify
![ouf](https://user-images.githubusercontent.com/30397475/35779235-9be5d3fc-0997-11e8-8b33-24af913f3e25.png)
 or remove this gray bar...

**Comment by Rainrider** [comment]
It is probably oUF_Karma, which does not seem to be updated for the current oUF version. The grey bar appears to be the health prediction bar. You will have to ask the author to update the layout or follow [oUF 7.0 upgrade guide](http://www.wowinterface.com/forums/showthread.php?t=55422) and fix it yourself.
