### ISSUE TITLE
[BFA] HONOR_PRESTIGE_UPDATE event cause error with the latest beta version.

### ISSUE THREAD

**Issue by Merathilis** [oUF-wow/oUF#435]
Hello friends,

with the latest beta build from Blizzard they seems to change/rename or deleted the Event HONOR_PRESTIGE_UPDATE.

Here is the error we got from ElvUI: 

`Message: Interface\AddOns\ElvUI\Libraries\oUF\events.lua:111: Attempt to register unknown event "HONOR_PRESTIGE_UPDATE"`

Reference: https://git.tukui.org/elvui/elvui/issues/406

**Comment by ls-** [comment]
Sup! I'll fix it tomorrow.

Prestige API was removed from the game, it's all about honour levels now.

**Comment by ls-** [comment]
I removed prestige entirely from the element. Basically, we reverted back to pre-Legion version.

I could replace prestige levels w/ honour levels, technically, it's the same stuff, unique PvP badges are still there as well, but a) Blizz no longer show prestige badges on their unit frames, they use only basic FfA, Alliance, and Horde badges now; b) honour API is still WIP. 

However, if there's demand, I'll add honour level support.

**Comment by Merathilis** [comment]
Thx for the quick fix. I don't know if there is a demand to add the honor level support, but i think it is good to have. ;)

**Comment by p3lim** [comment]
Apparently the prestige icons are hidden in FfA and neutral zones, but show otherwise.

**Comment by ls-** [comment]
Eh? They're "disabled" entirely in BfA. Both `*PrestigePortrait` and `*PrestigeBadge` are always hidden and unused, only basic Horde, Ally, and FFA PvP emblems are used.

**Comment by Rainrider** [comment]
Closed by b9560ee50984ab92a997fa4115e13aa2ff109acd
Feel free to re-open if something related arises.
