### ISSUE TITLE
Enhancement Request: Add parameter to oUF:Spawn() method to not hide blizzard unit on spawn.

### ISSUE THREAD

**Issue by runamonk** [oUF-wow/oUF#436]
Enhancement request in forum post:
http://www.wowinterface.com/forums/showthread.php?t=56197

May I ask project manager and authors to officially add an extra parameter to Spawn function (as above) so that the developers with oUF could choose to disable Blizzard default unitframe or not

**Comment by p3lim** [comment]
You can do this in the layout without having to modify the oUF source:
```lua
    -- store and disable the method
    local orig = oUF.DisableBlizzard
    oUF.DisableBlizzard = nop
     
    -- spawn your frames
    oUF:Spawn('player')
     
    -- re-enable the method
    oUF.DisableBlizzard = orig
```

**Comment by runamonk** [comment]
Yup, I just wish I had thought of overriding the original like that. I guess this can be closed out. :)
