### ISSUE TITLE
BFA Debuffs error

### ISSUE THREAD

**Issue by Wutname1** [oUF-wow/oUF#437]
Back in this commit 2c303ab488f42b67a5ef736c5d5094228f947bb2 line 201 was changed to use a different color table. This change is causing the following lua error for me on the BfA Beta

> 172x oUF\elements\auras-Auras.lua:203: attempt to index local 'color' (a nil value)

If i revert the code changes in this commit the error goes away and everything works as intended.

**Comment by ls-** [comment]
After a quick search in your repo I found this: https://github.com/Wutname1/SpartanUI/blob/BFA/libs/oUF_Plugins/oUF_DispelHighlight.lua#L43, your custom `debuff` table is incomplete which causes the issue you have.

**Comment by Wutname1** [comment]
Awesome, Great catch. Think i will just remove that plugin and swap over to Rainrider's Dispellable plugin.
