### ISSUE TITLE
MOTHER encounter!

### ISSUE THREAD

**Issue by Merathilis** [oUF-wow/oUF#455]
Hello folks,

on the MOTHER encounter in Uldir are different rooms. If player switch the rooms, they are Line of Sight. With the default Blizzard Frames the player shows as out of range if he is an another room. So you should take account to this.

A user from ElvUI just reported it back the behaviour with the Blizzard Frames.

**Comment by ls-** [comment]
Did I? O_o

**Comment by zorker** [comment]
I totally need to add that to my raid and party frames too.

**Comment by p3lim** [comment]
Just did the MOTHER fight on normal difficulty, the ranged element worked fine.
