### ISSUE TITLE
Boss Frames display issue.

### ISSUE THREAD

**Issue by Kkthnx** [oUF-wow/oUF#458]
Zork had started a thread over at wowinterface about a boss frame issue on MOTHER. Second boss in Uldir. I have tested this and it is indeed displaying weird. This also happens to the boss in deadmines, second boss that is where this display issue can and will happen as soon as you engage the boss. The second phase boss in deadmines will show a template like boss frame until he is officially off the back and engaged. Screenshots below and thread too.

Deadmines:
https://i.imgur.com/QFVyfyq.png

MOTHER (Uldir):
https://i.imgur.com/HfcNjei.jpg

Thread:
https://www.wowinterface.com/forums/showthread.php?t=56641

**Comment by ls-** [comment]
Hm, I think I've seen this bug as well, on KT in TK, when you pull him, his frame is like that till you're able to attack him after killing off his advisers.

**Comment by Kkthnx** [comment]
Yes, I forgot about this one.

**Comment by ls-** [comment]
I think the first time I've noticed it was when we released 8.0 for BfA. I'll go though oUF core changes we did for 8.0 either later today or tomorrow, I don't think element changes are causing the issue.

Thanks for mentioning the second boss in DM, it'll be much easier to test it fast/repeatedly.

**Comment by zorker** [comment]
Thanks for the Deadmine boss info. Was looking for a boss to test it with aswell. M.O.T.H.E.R. is kinda hard to test.

**Comment by ls-** [comment]
K, I know where the issue is.
