### ISSUE TITLE
Tag showing incorrect numbers

### ISSUE THREAD

**Issue by Dajova** [oUF-wow/oUF#473]
So i should have made this ticket ages ago, but forgot about it...

Anyway, these tags:
`incomingheals
incomingheals:personal
incomingheals:others`
.... doesn't work as intended. They display double the amount than what's actually healed, like it's calculating it's gonna crit by default.

For example, if i cast Healing Wave, it heals for 10k, but the tag says 20k.

**Comment by p3lim** [comment]
These tags are not implemented by oUF, so this is something we're not in control of.
