### ISSUE TITLE
 Interface\AddOns\ElvUI\Libraries\oUF\ouf.lua:791: attempt to call method 'UpdateAllElements' (a nil value)

### ISSUE THREAD

**Issue by jefflenz** [oUF-wow/oUF#488]
Getting this error every few seconds while moving character

Message: Interface\AddOns\ElvUI\Libraries\oUF\ouf.lua:791: attempt to call method 'UpdateAllElements' (a nil value)
Time: Wed Mar 13 20:49:06 2019
Count: 3
Stack: Interface\AddOns\ElvUI\Libraries\oUF\ouf.lua:791: attempt to call method 'UpdateAllElements' (a nil value)
[C]: in function `UpdateAllElements'
Interface\AddOns\ElvUI\Libraries\oUF\ouf.lua:791: in function <Interface\AddOns\ElvUI\Libraries\oUF\ouf.lua:746>

**Comment by jefflenz** [comment]
Not sure if this is really a bug or not, but this turned out to be because I'm using Plater Nameplates

**Comment by ls-** [comment]
From what I can tell, you're running Plater while having ElvUI nameplates, that now use oUF, enabled, which is a very bad idea, so obviously it ended up causing issues.
