### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by p3lim** [oUF-wow/oUF#495]
- options are already optional, drop the `?` from the type, suggesting something else than the type could be provided
- when the option requires a specific value, explicitly note the value instead of the type
   - e.g. `('asc'|'desc'|nil)` instead of `(string?) ['asc', 'desc']` (current)
   - right-most type is the default value (typically `nil`)
- types should be presented before the explanation of the option
   - e.g. `(string|nil) ...` instead of `... (string?)` (current)

We also need to (finally) export the documentation.

**Comment by siweia** [comment]
The doc in stagger may need to be improved as well.
https://github.com/oUF-wow/oUF/blob/5a201c9afa0938d81e43a3cc7873561e5199ace1/elements/stagger.lua#L140
The UNIT_AURA can only be registered if you hide the stagger by default.

**Comment by Rainrider** [comment]
Do not show/hide oUF elements by yourself, let oUF handle this.

**Comment by siweia** [comment]
If I follow the example doc in stagger, the bar won't be able to update.
I have to add "Stagger:Hide()".

**Comment by Rainrider** [comment]
Nope, this is something I've broken [here](https://github.com/oUF-wow/oUF/commit/8d49274e76915836f962514ab8f7447fe819d332), it is not the docs. Will fix in about an hour.

**Comment by Rainrider** [comment]
The patch is pending approval and will be released shortly. I am sorry for the inconvenience it has caused you. Thanks for reporting it.

**Comment by p3lim** [comment]
Stupid GitHub trying to be smart...
