### ISSUE TITLE
Party frames Hide Player not working in arenas

### ISSUE THREAD

**Issue by danonji** [oUF-wow/oUF#503]
Hey there,

Unfortunately, for some reason, you can't hide player from party frames while you are in arena

Thanks hopefully there is a fix or work around.

**Comment by Rainrider** [comment]
Could you share a link to your layout code or paste the relevant parts here?

**Comment by Rav99** [comment]
Hiho.
I hope i paste the correct link to the layoutcode:
https://github.com/Kkthnx/KkthnxUI/blob/066bc3f89bc079ff513f7a6080f577d4c565bc22/KkthnxUI/Modules/UnitFrames/Core.lua#L1107

Thx for help!

**Comment by Rainrider** [comment]
It is rather [this](https://github.com/Kkthnx/KkthnxUI/blob/066bc3f89bc079ff513f7a6080f577d4c565bc22/KkthnxUI/Modules/UnitFrames/Core.lua#L1121) controlling the display of the player frame as part of the party frames.
It is set to true by default in this layout ([ref](https://github.com/Kkthnx/KkthnxUI/blob/8a63cac9ec32754c8e8b030f27f9a501606e2363/KkthnxUI/Config/Settings.lua#L591))

**Comment by Rav99** [comment]
yeah but if we set it to false in config or manually in code "showPlayer", false, it shows the player in raid/arena

**Comment by Rainrider** [comment]
Do I understand correctly that after setting `showPlayer` to `false` the player frame is does not appear among the party frames but pops back in when you join an arena?

**Comment by Rav99** [comment]
Right and in raid too.

**Comment by Rainrider** [comment]
Using `custom [group:party] show; hide` as visibility condition and not using the `showPlayer` attribute on my layout spawns the group header without the player frame. The `showPlayer` attribute has no effect on raid headers. Please consult the author of the layout to provide a solution for you.
