### ISSUE TITLE
Interface\AddOns\oUF\events.lua:146: Attempt to register unknown event "PLAYER_TALENT_UPDATE"

### ISSUE THREAD

**Issue by cikichen** [oUF-wow/oUF#505]
```
Interface\AddOns\oUF\events.lua:146: Attempt to register unknown event "PLAYER_TALENT_UPDATE"
Count: 1

Call Stack:
[C]: ?
Interface\AddOns\oUF\events.lua:146: in function `RegisterEvent'
Interface\AddOns\oUF_Abu\Modules\oUF_Aurabars.lua:124: in function `enable'
Interface\AddOns\oUF\ouf.lua:113: in function `EnableElement'
Interface\AddOns\oUF\ouf.lua:343: in function <Interface\AddOns\oUF\ouf.lua:260>
(tail call): ?
Interface\AddOns\oUF\ouf.lua:728: in function `Spawn'
Interface\AddOns\oUF_Abu\Layout.lua:917: in function `func'
Interface\AddOns\oUF\factory.lua:20: in function <Interface\AddOns\oUF\factory.lua:16>
(tail call): ?
```

`oUF-1.5.16`

**Comment by p3lim** [comment]
Which version of WoW are you using?

**Comment by Rainrider** [comment]
`[oUF-1.5.16](https://github.com/oUF-wow/oUF/commit/a0f4ae8db497206cc7f3e226cf3fcb299f419bd1)` Cataclysm? Private server?

**Comment by cikichen** [comment]
> Which version of WoW are you using?

8.1.5.30706

**Comment by p3lim** [comment]
You're using an 8 year old version of oUF, update.

**Comment by p3lim** [comment]
Also top comment here is relevant: https://www.wowinterface.com/downloads/info23020-oUFAbu.html#comments

Author of the layuout hasn't updated oUF.

**Comment by cikichen** [comment]
@p3lim 

```
## Interface: 80100
## Title: oUF
## Author: Haste, lightspark, p3lim, Rainrider
## Version: @project-version@
## Notes: Unit frame framework. Does nothing by itself.
## OptionalDeps: Clique
## X-oUF: oUF

## X-Curse-Project-ID: 21187
## X-WoWI-ID: 9994

oUF.xml
```

**Comment by p3lim** [comment]
That's the TOC file from a development version of oUF, it doesn't say anywhere how old it is.
Stick to releases from either CurseForge or WoWInterface.

**Comment by cikichen** [comment]
@p3lim I get it from twitch. ouf-9.2.0

**Comment by cikichen** [comment]
![image](https://user-images.githubusercontent.com/1478821/59551913-5df89180-8fb3-11e9-803d-6c1d131a44bd.png)

**Comment by p3lim** [comment]
The layout still isn't updated for that version of oUF, which is why I linked to the comment section of the layout.

**Comment by ls-** [comment]
Sup o7

Given the error msg:
```
Interface\AddOns\oUF\events.lua:146: in function `RegisterEvent'
Interface\AddOns\oUF_Abu\Modules\oUF_Aurabars.lua:124: in function `enable'
```
the issue is caused by `oUF_Aurabars`, however, `"PLAYER_TALENT_UPDATE"` is a legit event on live and test realms. Which means that you're running it in the environment where it doesn't exist. PS? Classic Beta?

Either way, it's unrelated to oUF itself.

**Comment by ls-** [comment]
One a side note, the layout in question isn't designed for oUF 9.x.x, there's some changes to the event system and the framework's core in general. So you should use oUF 8.x.x.
