### ISSUE TITLE
1.13, What should be done?

### ISSUE THREAD

**Issue by Industrial** [oUF-wow/oUF#518]
Hi!

Let's patch oUF for 1.13! Where to start?

:-)

**Comment by Wutname1** [comment]
The oUF team's official stance is that they will not be supporting classic. https://www.wowinterface.com/forums/showthread.php?p=333609

You can look at ElvUI's repo for forks support only 1 wow version each. I have been working on my own fork https://github.com/Wutname1/SUF that supports both retail and classic in 1.

**Comment by Industrial** [comment]
I've written a reply there too. I think development efforts could be centralized.

I'm going to try TukUI's changes today in my fork and then ElvUI's and your changes in branches as well :-)

I would be fine with merging code from all the different repos/versions into one. My preference would also be to support both Live and Classic. This would be the easiest for everyone (devs and users). 

What do you think about this?

gr,

Tom

**Comment by Azilroka** [comment]
I have been working on a pure classic one. The differences are quite substantial in some modules.
