### ISSUE TITLE
Issue identifying unit when using `SpawnHeader`

### ISSUE THREAD

**Issue by chiel** [oUF-wow/oUF#535]
Hello again! This is more of a question, rather than an issue. I'm sorry for posting here but I tried asking in the WoW AddOns discord without much luck.

In my UI I'm currently spawning some party frames and that is all working just fine, but I want to make a small change which is to show a power bar only for the healer in my party, however during the initial spawn the `unit` is always set to `party` rather than `player` or `partyN`. I assume this is on purpose and I need to react to some kind of event to make the desired change, however I could not find any documentation about this.

Additionally I'll be creating some raid frames after this and I was wondering what the best way is to get a "grid"-like layout where each group is next to each other. Should I spawn each group as a separate header? I'd like to be able to change things up based on the amount of groups and my currently selected spec (healer vs other roles in particular) - I'd appreciate any advice you can give for this.

Sorry again for asking the question here, if there's a better place to pose these kinds of questions I'll happily ask there!

Cheers.

**Comment by Rainrider** [comment]
The preferred way for us it ask questions on wowinterface.com in the oUF forum section. The community can help there as well.

For healer power bars: [this is how p3lim does it his layout](https://github.com/p3lim-wow/oUF_P3lim/blob/0ca02aa4ea27e9681767cd1925bac15140695753/oUF_P3lim.lua#L23-L42).

For grid-like raid layout: [this is how I do it in my layout](https://github.com/Rainrider/oUF_Layout/blob/90ed317a45045e0e0a2046d768acdd601a503a35/layout.lua#L110-L132).

**Comment by chiel** [comment]
Okay cool, will head there from now on - thanks again!
