### ISSUE TITLE
[Feature request] Make combat indicator usable for every unit, not only for player

### ISSUE THREAD

**Issue by Solor** [oUF-wow/oUF#541]
at least for target and focus
combat state is essential for rogue in arena and rbg

**Comment by ls-** [comment]
Is it even possible to get enemy players' combat state? O_o It works for mobs, although not super reliably, but players... And I've just checked Gladius and its forks code and there's no feature like that either.

**Comment by Solor** [comment]
according to wowpedia, UnitAffectingCombat works for hostile target o_O

**Comment by ls-** [comment]
Tbhon, hostile target != hostile player. There's always various restrictions regarding enemy players. As I said, it works for hostile mobs, although a bit quirky, but I haven't seen anyone use it in PvP addons like Gladius(Ex), sArena, or BattlegroundTargets. I haven't even seen combat icons in those in recent years either.

**Comment by Solor** [comment]
Ok, thanks for explain this 👌
