### ISSUE TITLE
Monk stagger power update

### ISSUE THREAD

**Issue by siweia** [oUF-wow/oUF#553]
https://github.com/oUF-wow/oUF/blob/master/elements/stagger.lua#L158

The event UNIT_AURA only register when stagger bar is hidden.
Should we hide the bar in layout  as default, or let oUF handle it?

**Comment by ls-** [comment]
Sup! Yeah, it's brought to my attention 1-2 days ago. I actually want to rewrite that `Visibility` function to make it work/look similar to how `Visibility` behaves in other elements like additional and class powers.

**Comment by ls-** [comment]
But for now, yes, when creating the widget, you're expected to hide it.

**Comment by Rainrider** [comment]
Actually [this](https://github.com/oUF-wow/oUF/commit/eeed238999eb6efd13c40e0cba8640e78e294d3e#diff-be1f7c7df1888c72ee91aa11ec7348b8e477842adfe3921ed811f0fa173a5e71) @ls- 

Layouts should not depend on our internal logic. Fixing this is as easy as adding `element:Hide()` in Enable.

**Comment by ls-** [comment]
I still want to revamp that visibility and add callbacks.
