### ISSUE TITLE
Portraits not updating properly?

### ISSUE THREAD

**Issue by Kkthnx** [oUF-wow/oUF#564]
**Describe the bug**

When I shift into Storm, Earth, and Fire as a Monk. My portraits should change as my model does. Yet sometimes they do not update when I shift into this new model and sometimes they do. If I re-target myself, it will update it.

Do note I do not recall any changes I have made to KkthnxUI to affect this. I remember a bug report I made maybe around a year ago about the same issue which was solved though I did not see this issue again until Prepatch.

**How to reproduce**

I guess you could use a toy to shift into a different model or use the said spell above on a monk in Windwalker spec.

**What did you expect?**

Portraits should update based on your model change and not stick to a previous change model after you left that model or changed into a different model.

**Error report**

```
```

**Screenshots**

![unknown](https://user-images.githubusercontent.com/40672673/98429643-ed558780-2075-11eb-8435-bdc11b069c34.png)
![unknown](https://user-images.githubusercontent.com/40672673/98429647-f6deef80-2075-11eb-8640-0e366a483e56.png)

**Comment by ls-** [comment]
Sup!

I'm not exactly sure what to do about portraits, they've been a pita for quite a while. Thing is, no portrait-related events fire when you cast that spell, so it doesn't update. The same happens in the default UI, btw.

![image](https://user-images.githubusercontent.com/2725970/98434010-6698bd00-20fe-11eb-9982-3d69a4d8fc53.png)

The only solution I see so far is to try to use `UNIT_AURA`, but it's a VERY spammy event, and frequent updates of 3D portraits can cause stuttering which isn't ideal.

**Comment by Kkthnx** [comment]
That is rough. Honestly, it is so minor that I was debating on reporting it. Though UNIT_AURA honestly is not worth it. I mean if people really care they can do this themselves. Thank you kindly though for the reply and looking into it nonetheless <3

**Comment by ls-** [comment]
I'll be closing it then. And have a nice day.

**Comment by goldpaw** [comment]
Not to necro a closed thread, but we did some more testing, and it turns out a ton of model changes from toys are left out of portrait updates too. So "fixing" this would require a huge list of auraIDs to track, not to mention constantly monitoring `UNIT_AURA` for this. 

So I say screw it! The portrait reflects shapeshifts and vehicles. That's enough.

**Comment by ls-** [comment]
What surprises me is that for some reason it doesn't count as a model change, `UNIT_MODEL_CHANGED` doesn't fire 🤔 Oh well...
