### ISSUE TITLE
Entering arena while in combat generates error, no arena# frames

### ISSUE THREAD

**Issue by catthou** [oUF-wow/oUF#576]
**Describe the bug**
Entering an arena while in combat generates a UI error and the arena frames won't be shown during arena preparation.

**How to reproduce**
1. Use an oUF layout that has arena frames.
2a. Queue for arenas or arena skirmish. 
2b. Engage in combat with a target dummy, or any mob.
3. Click "enter" on the arena queue popup while in combat.
4. Success! No unit frames and a bug in the bugsack

**What did you expect?**
I wouldn't expect there to be any issue generating arena frames since I'll have(hopefully?) left combat as soon as I phased out of the open-world.

**Error report**

```
1x [ADDON_ACTION_BLOCKED] AddOn 'oUF' tried to call the protected function 'SecureStateDriverManager:SetAttribute()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML\SecureStateDriver.lua"]:48: in function `UnregisterUnitWatch'
[string "@oUF\ouf-10.0.3.lua"]:178: in function `Disable'
[string "@oUF\units.lua"]:136: in function <oUF\units.lua:98>
[string "=[C]"]: ?
```

My layout is using a for loop to generate the frames, but I don't know if that has any importance:
```
local Arena = {}
for n=1, MAX_ARENA_FRAMES or 5 do
Arena[n] = self:Spawn("arena" .. n, addonName .. "arenaFrame" .. n)
--SetPoint(), etc
end
```

**Comment by p3lim** [comment]
While the error is presented by the arena prep code I made, we should probably look into ensuring the player is not in combat lockdown when disabling a frame.

**Comment by catthou** [comment]
Let me know if I can help contribute anything else. I do arenas regularly so it wouldn't be out of my way to test fixes.

**Comment by wing5wong** [comment]
Jumping in to track this - using elvui with a similar issue where arena prep frames sometimes do not appear.
Unable to reproduce this exact use case with elvui though following the given steps

**Comment by p3lim** [comment]
@catthou Sorry for the delayed response, are you still experiencing this issue?
