### ISSUE TITLE
AddElement arguments requirement inconsistencies.

### ISSUE THREAD

**Issue by gizzmo** [oUF-wow/oUF#579]
The AddElement method says that the `Update`, `Enable`, and `Disable` functions are optional. But according to the code, they're not. I assume they're not meant to be, and it's just an incorrect docs issue.
https://github.com/oUF-wow/oUF/blob/abdc99e879413ed65ac6d6c56c0c5eac7de8bac4/ouf.lua#L852-L860

https://github.com/oUF-wow/oUF/blob/abdc99e879413ed65ac6d6c56c0c5eac7de8bac4/ouf.lua#L113
https://github.com/oUF-wow/oUF/blob/abdc99e879413ed65ac6d6c56c0c5eac7de8bac4/ouf.lua#L144

So `Update` can be optional
https://github.com/oUF-wow/oUF/blob/abdc99e879413ed65ac6d6c56c0c5eac7de8bac4/ouf.lua#L116-L118
But it would make this loop pointless.
https://github.com/oUF-wow/oUF/blob/abdc99e879413ed65ac6d6c56c0c5eac7de8bac4/ouf.lua#L134-L140

Bonus bug I just noticed. The arg number is wrong in those `argcheck` calls

**Comment by gizzmo** [comment]
So Update can be optional:
https://github.com/oUF-wow/oUF/blob/abdc99e879413ed65ac6d6c56c0c5eac7de8bac4/ouf.lua#L116-L118
But it would make this loop pointless.
https://github.com/oUF-wow/oUF/blob/abdc99e879413ed65ac6d6c56c0c5eac7de8bac4/ouf.lua#L134-L140

**Comment by Rainrider** [comment]
The documentation is not wrong, it's the code

https://github.com/oUF-wow/oUF/blob/abdc99e879413ed65ac6d6c56c0c5eac7de8bac4/ouf.lua#L858-L860

It explicitly allows for nil. I'll take a look at it later just to make sure it does not break something and fix accordingly.

> Bonus bug I just noticed. The arg number is wrong in those `argcheck` calls

Nope, self is the first argument.

`thing:func(arg2, arg3)` is syntactic sugar for `thing.func(thing, arg2, arg3)`

**Comment by gizzmo** [comment]
>Nope, self is the first argument.
Ah yeah, forgot about that.
