### ISSUE TITLE
Different display name for castbars

### ISSUE THREAD

**Issue by siweia** [oUF-wow/oUF#608]
https://github.com/tomrus88/BlizzardInterfaceCode/blob/4334b87a5365523a8d5211fba0819818946a967f/Interface/FrameXML/CastingBarFrame.lua#L171-L173
In blizzard default UI, they use the second return value for castbar name.
Normally name and text share the same string, but some spells might have more info from text.

Here is the dump for the spell when opening the weekly rewards in Great Vault.

Dump: value=UnitCastingInfo("player")
[1]="Opening",
[2]="Generating loot for Marksmanship",
[3]=3536198,
[4]=11045567,
[5]=11050567,
[6]=false,
[7]="Cast-3-4608-2222-5-343885-000DE16769",
[8]=false,
[9]=343885

**Comment by ls-** [comment]
Hi, thanks for bringing it up! Keep forgetting about this one.
