### ISSUE TITLE
Empowered casts on friendly nameplates cause errors

### ISSUE THREAD

**Issue by th657** [oUF-wow/oUF#614]
The following error happens when an empowered cast happens on friendly nameplates:
`
StatusBar:GetRight(): Action[FrameMeasurement] failed because[Can't measure restricted regions]: attempted from: StatusBar:GetRight()
`
It could happen on enemy nameplates too but I haven't checked.

The error is caused by
https://github.com/oUF-wow/oUF/blob/f1a64788b08a41821dca6dbc954c5151f36b284e/elements/castbar.lua#L119

Changing the line to `local elementWidth = element:GetWidth()` seems to work fine.

**Comment by p3lim** [comment]
Thanks for the report, didn't think to test on friendly nameplates.
