### ISSUE TITLE
range.lua The party frame uses the portrait. When the distance is exceeded, the portrait will not be translucent

### ISSUE THREAD

**Issue by dwWei** [oUF-wow/oUF#627]
hi
The party frame uses the portrait. When the distance is exceeded, the portrait will not be translucent
9.0 No problem

**Comment by ls-** [comment]
It’s a known Blizz bug. There’s nothing we can do. See https://github.com/Stanzilla/WoWUIBugs/issues/295 for more info, just don’t comment there.
