### ISSUE TITLE
Incorrect dot stacks for the first cast

### ISSUE THREAD

**Issue by siweia** [oUF-wow/oUF#633]
**Describe the bug**
The [Festering Strike](https://www.wowhead.com/spell=85948/festering-strike) would affect dot 'Festering Wound' to target.
It suppose to be 2 to 3 stacks when you cast Festering Strike for the first time, but only one stack by ouf/auras.

**How to reproduce**
Create a unholy DK trial account, and cast Festering Strike.

**What did you expect?**
Correct spell stacks for first cast.

**Error report**
No.

**Screenshots**
No.

**Comment by ls-** [comment]
I see what's going on 🤔
