### ISSUE TITLE
Additional Power/Spawn Frame issue?

### ISSUE THREAD

**Issue by Aideenwolf** [oUF-wow/oUF#649]
**Describe the bug**
Screen is all black and most UI elements will not load

**How to reproduce**
This may be a me issue - I'm limping along with a UI layout that's no longer supported just tryin to make it work. 
The error comes from this line in my code
```
oUF:Spawn("player", "oUF_DrkPlayerFrame")
```

**What did you expect?**
UI frame to work ;)

**Error report**

```
1x SharedXML/TableUtil.lua:238: bad argument #1 to 'pairs' (table expected, got nil)
[string "=[C]"]: in function `pairs'
[string "@SharedXML/TableUtil.lua"]:238: in function `CopyTable'
[string "@oUF/elements/additionalpower.lua"]:275: in function `enable'
[string "@oUF/ouf.lua"]:100: in function `EnableElement'
[string "@oUF/ouf.lua"]:342: in function <oUF/ouf.lua:258>
[string "=(tail call)"]: ?
[string "@oUF/ouf.lua"]:736: in function `Spawn'
[string "@oUF_Drk/units/player.lua"]:557: in main chunk

Locals:
(*temporary) = nil
(*temporary) = "table expected, got nil"
 = <function> defined =[C]:-1
```

**Screenshots**

**Comment by ls-** [comment]
Hi! You either updated to the latest oUF from github too soon, or you're on 10.1.5 and using an out of date version. That part was changed because of 10.1.5 in #647.

**Comment by Aideenwolf** [comment]
Yeah this is a strange one for me. I am in the 10.1.5 and using the current master from github.
Still getting the black screen of death.
Sometimes it gives me the above error a lot of the time it just doesn't give me any error at all. So it makes it harder to troubleshoot.  I'm not the best coder - so it's very possible that I might just have to give up on my frame and use one from someone that knows what they are doing

**Comment by Aideenwolf** [comment]
just goin to write it off as an abandoned layout and not worth trying to update  :) Thank you all for taking a look
