### ISSUE TITLE
ReadyCheckIndicator no longer displays icons (wow 10.1.5)

### ISSUE THREAD

**Issue by calmbook1300** [oUF-wow/oUF#651]
**Describe the bug**
On retail the `ReadyCheckIndicator` element no longer displays icons on unit frames.

I assume this is because the READY_CHECK_ globals now contain atlas keys. e.g. the value of READY_CHECK_READY_TEXTURE is now "UI-LFG-ReadyMark".  Locally I have just replaced calls to `element:SetTexture` with `element:SetAtlas` as a temporary but not backward compatible workaround.

**How to reproduce**
Perform a ready check in a party or raid.  

**What did you expect?**
Ready check status icons should appear on party and raid unit frames.

**Error report**
N/A

**Comment by ls-** [comment]
Thanks!
