### ISSUE TITLE
On paladin I get several attempt to index field 'X' (a nil value)

### ISSUE THREAD

**Issue by arnvid** [oUF-wow/oUF#671]
**Describe the bug**
Did LFR with Retribution paladin, oUF spews errors.

**How to reproduce**
Raid with paladin.

**What did you expect?**
Not to have eerors:

**Error report**
x176  Interface/AddOns/oUF/elements/auras.lua:373: attempt to index field 'allDebuffs' (a nil value)
Stack: [string "@Interface/AddOns/oUF/elements/auras.lua"]:373: in function <Interface/AddOns/oUF/elements/auras.lua:289>
[string "=(tail call)"]: ?
Time: 2024/01/23 23:46:57 Index: 4/6
Locals:
Skipped (In Encounter)

x137  Interface/AddOns/oUF/elements/auras.lua:406: attempt to index field '21' (a nil value)
Stack: [string "@Interface/AddOns/oUF/elements/auras.lua"]:406: in function <Interface/AddOns/oUF/elements/auras.lua:289>
[string "=(tail call)"]: ?
Time: 2024/01/23 23:47:00 Index: 3/6
Locals:
Skipped (In Encounter)

x5  Interface/AddOns/oUF/elements/auras.lua:365: attempt to index field 'allBuffs' (a nil value)
Stack: [string "@Interface/AddOns/oUF/elements/auras.lua"]:365: in function <Interface/AddOns/oUF/elements/auras.lua:289>
[string "=(tail call)"]: ?
Time: 2024/01/23 23:47:40 Index: 2/6
Locals:
Skipped (In Encounter)

**Comment by ls-** [comment]
This is a very weird issue.

Under normal circumstances, it shouldn't be able to get to that part the way it did in your case without doing a full update first. Like, the update function will see `ForceUpdate` or `OnShow` first both of which cause a full update to happen where all the needed tables are created, but for whatever reason it didn't happen in your particular case, and somehow `UNIT_AURA` got there first.

Need more info on this one. Which frames were causing the error? Which layout are you using? You posted 3 out of 6 errors you got there, what were the others? It seems to be a standalone oUF install on top of all that which is kinda unconventional 🤔

**Comment by arnvid** [comment]
This is from oUF as included in RealUI. Bug 1 was always a bug that came from RealUI_Dev. Other bugs were not related and not added..

After upgrading to latest oUF - and now the realui dev code base the error changed to

x2212  [string "return function(u)..."]:2: Usage: local r, g, b = GetThreatStatusColor(gameErrorIndex)
Stack: [string "=[C]"]: in function 'GetThreatStatusColor'
[string "return function(u)
    	return Hex(GetThreatStatusColor(UnitThreatSituation(u)))
    end"]:2: in function 'threatcolor'
[string "@Interface/AddOns/RealUI_Core-2.3.11/HuD/UnitFrames/Tags.lua"]:210: in function 'f'
[string "@Interface/AddOns/oUF/elements/tags.lua"]:792: in function 'UpdateTag'
[string "@Interface/AddOns/oUF/elements/tags.lua"]:668: in function 'func'
[string "@Interface/AddOns/oUF/ouf.lua"]:200: in function <Interface/AddOns/oUF/ouf.lua:183>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/oUF/ouf.lua"]:218: in function <Interface/AddOns/oUF/ouf.lua:217>
[string "=[C]"]: in function 'Show'
[string "@Interface/FrameXML/SecureStateDriver.lua"]:83: in function <Interface/FrameXML/SecureStateDriver.lua:73>
[string "@Interface/FrameXML/SecureStateDriver.lua"]:137: in function <Interface/FrameXML/SecureStateDriver.lua:119>

**Comment by arnvid** [comment]
There reason why it looks to be "standalone" is the way that RealUI Development setup is built vs how RealUI is distributed.
