### ISSUE TITLE
Range indicator not working for player

### ISSUE THREAD

**Issue by Nils89** [oUF-wow/oUF#683]
With the TWW update, the player itself will always been shown out of range.

This is how I set up the Range indicator:
local function Construct_RangeIndicator(frame)
    local range = {
        insideAlpha = 1,
        outsideAlpha = 0.2,
    }

	return range
end

**Screenshots**
https://cdn.discordapp.com/attachments/736635782521028711/1265784554631991387/image.png?ex=66a2c53a&is=66a173ba&hm=c9d7e427c72209ac3e72127fa98faca6d6cf571687b539c9a2d456f2ef1ed25c&

**Comment by ls-** [comment]
Oof, yeah, I forgot to fix one last thing while updating the element for TWW.

**Comment by p3lim** [comment]
12.0.1 pushed with the fix.
